-- Migration to fix IFA table schema and ensure all columns exist
-- Based on user provided schema with BIGINT id

-- 0. Create Log Functions (Auditoria)
CREATE OR REPLACE FUNCTION public.log_insert_ifa()
RETURNS TRIGGER AS $$
DECLARE
  v_auth_id uuid := auth.uid();
  v_usuario_id uuid;
  v_empresa_id bigint;
BEGIN
  SELECT id, empresa_id INTO v_usuario_id, v_empresa_id
  FROM usuarios
  WHERE auth_id = v_auth_id;

  INSERT INTO logs_auditoria (
    empresa_id,
    usuario_id,
    acao,
    tabela,
    registro_id,
    dados_antes,
    dados_depois,
    ip
  )
  VALUES (
    v_empresa_id,
    v_usuario_id,
    'insert',
    'ifa',
    NEW.id::text,
    null,
    to_jsonb(NEW),
    null
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public';

CREATE OR REPLACE FUNCTION public.log_update_ifa()
RETURNS TRIGGER AS $$
DECLARE
  v_auth_id uuid := auth.uid();
  v_usuario_id uuid;
  v_empresa_id bigint;
BEGIN
  SELECT id, empresa_id INTO v_usuario_id, v_empresa_id
  FROM usuarios
  WHERE auth_id = v_auth_id;

  INSERT INTO logs_auditoria (
    empresa_id,
    usuario_id,
    acao,
    tabela,
    registro_id,
    dados_antes,
    dados_depois,
    ip
  )
  VALUES (
    v_empresa_id,
    v_usuario_id,
    'update',
    'ifa',
    NEW.id::text,
    to_jsonb(OLD),
    to_jsonb(NEW),
    null
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public';

CREATE OR REPLACE FUNCTION public.log_delete_ifa()
RETURNS TRIGGER AS $$
DECLARE
  v_auth_id uuid := auth.uid();
  v_usuario_id uuid;
  v_empresa_id bigint;
BEGIN
  SELECT id, empresa_id INTO v_usuario_id, v_empresa_id
  FROM usuarios
  WHERE auth_id = v_auth_id;

  INSERT INTO logs_auditoria (
    empresa_id,
    usuario_id,
    acao,
    tabela,
    registro_id,
    dados_antes,
    dados_depois,
    ip
  )
  VALUES (
    v_empresa_id,
    v_usuario_id,
    'delete',
    'ifa',
    OLD.id::text,
    to_jsonb(OLD),
    null,
    null
  );

  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public';

DO $$
BEGIN
    -- 1. Create table if it doesn't exist
    CREATE TABLE IF NOT EXISTS public.ifa (
        id bigint generated by default as identity not null PRIMARY KEY,
        ifa text null,
        fabricante text null,
        dcb text null,
        lote text null,
        empresa_id bigint not null default get_current_user_empresa_id(),
        data_fabricacao date null,
        data_validade date null,
        numero_cas text null,
        endereco_fabricante text null,
        created_at timestamp with time zone not null default now(),
        updated_at timestamp with time zone null default now()
    );

    -- 2. Add columns if they don't exist (for existing table)
    
    -- ifa
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'ifa') THEN
        ALTER TABLE public.ifa ADD COLUMN ifa text null;
    END IF;

    -- fabricante
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'fabricante') THEN
        ALTER TABLE public.ifa ADD COLUMN fabricante text null;
    END IF;

    -- dcb
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'dcb') THEN
        ALTER TABLE public.ifa ADD COLUMN dcb text null;
    END IF;

    -- lote
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'lote') THEN
        ALTER TABLE public.ifa ADD COLUMN lote text null;
    END IF;

    -- empresa_id
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'empresa_id') THEN
        ALTER TABLE public.ifa ADD COLUMN empresa_id bigint not null default get_current_user_empresa_id();
        -- Add FK
        ALTER TABLE public.ifa ADD CONSTRAINT ifa_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id);
    END IF;

    -- data_fabricacao
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'data_fabricacao') THEN
        ALTER TABLE public.ifa ADD COLUMN data_fabricacao date null;
    END IF;

    -- data_validade
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'data_validade') THEN
        ALTER TABLE public.ifa ADD COLUMN data_validade date null;
    END IF;

    -- numero_cas
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'numero_cas') THEN
        ALTER TABLE public.ifa ADD COLUMN numero_cas text null;
    END IF;

    -- endereco_fabricante
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'endereco_fabricante') THEN
        ALTER TABLE public.ifa ADD COLUMN endereco_fabricante text null;
    END IF;

    -- updated_at
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'ifa' AND column_name = 'updated_at') THEN
        ALTER TABLE public.ifa ADD COLUMN updated_at timestamp with time zone null default now();
    END IF;

END $$;

-- 3. Add Triggers (drop first to ensure clean state)
DROP TRIGGER IF EXISTS trg_log_delete_ifa ON public.ifa;
CREATE TRIGGER trg_log_delete_ifa
    AFTER DELETE ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_delete_ifa();

DROP TRIGGER IF EXISTS trg_log_insert_ifa ON public.ifa;
CREATE TRIGGER trg_log_insert_ifa
    AFTER INSERT ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_insert_ifa();

DROP TRIGGER IF EXISTS trg_log_update_ifa ON public.ifa;
CREATE TRIGGER trg_log_update_ifa
    AFTER UPDATE ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_update_ifa();

-- 4. Enable RLS
ALTER TABLE public.ifa ENABLE ROW LEVEL SECURITY;

-- 5. Add Policies (Standard for company isolation)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ifa' AND policyname = 'Company isolation for ifa') THEN
        CREATE POLICY "Company isolation for ifa" ON public.ifa
            USING (empresa_id = get_current_user_empresa_id())
            WITH CHECK (empresa_id = get_current_user_empresa_id());
    END IF;
END $$;
