-- Migration to fix IFA table schema and amostra_ifas relationship
-- Based on user provided schema with BIGINT id for ifa

-- 1. Drop existing triggers and functions if necessary (already handled in previous scripts but good to be safe)
DROP TRIGGER IF EXISTS trg_log_delete_ifa ON public.ifa;
DROP TRIGGER IF EXISTS trg_log_insert_ifa ON public.ifa;
DROP TRIGGER IF EXISTS trg_log_update_ifa ON public.ifa;

-- 2. Ensure ifa table uses BIGINT for id
-- Since we cannot easily convert UUID to BIGINT if there is data, we will:
-- a) Check if column is UUID
-- b) If so, drop table and recreate (assuming development environment or acceptable data loss for this table which seems to be auxiliary)
--    OR we try to alter it. Given the error "invalid input syntax for type bigint: UUID", it seems the table might actually be returning UUIDs?
--    Wait, if the table definition in DB is UUID, then `ifaCriado.id` is UUID.
--    But `amostra_ifas.ifa_id` is BIGINT.
--    So we MUST change `ifa.id` to BIGINT.

DO $$
BEGIN
    -- Check if id column is UUID
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'ifa' 
        AND column_name = 'id' 
        AND data_type = 'uuid'
    ) THEN
        -- We need to change it. Since it's a PK referenced by other tables, we need to be careful.
        -- Drop dependent constraints first
        ALTER TABLE public.amostra_ifas DROP CONSTRAINT IF EXISTS unique_amostra_ifa;
        -- We might need to drop the column in amostra_ifas that references it? 
        -- Actually amostra_ifas.ifa_id is BIGINT, so it doesn't reference ifa.id if ifa.id is UUID (types mismatch).
        -- So there is likely NO foreign key constraint currently active between them, or it's broken.
        
        -- Let's drop and recreate the ifa table to be clean and match user schema exactly.
        DROP TABLE public.ifa CASCADE;
        
        -- Recreate table with correct schema
        CREATE TABLE public.ifa (
            id bigint generated by default as identity not null PRIMARY KEY,
            ifa text null,
            fabricante text null,
            dcb text null,
            lote text null,
            empresa_id bigint not null default get_current_user_empresa_id(),
            data_fabricacao date null,
            data_validade date null,
            numero_cas text null,
            endereco_fabricante text null,
            created_at timestamp with time zone not null default now(),
            updated_at timestamp with time zone null default now(),
            CONSTRAINT ifa_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id)
        );
        
        -- Re-enable RLS
        ALTER TABLE public.ifa ENABLE ROW LEVEL SECURITY;
        
        -- Re-add policy
        CREATE POLICY "Company isolation for ifa" ON public.ifa
            USING (empresa_id = get_current_user_empresa_id())
            WITH CHECK (empresa_id = get_current_user_empresa_id());
            
    END IF;
END $$;

-- 3. Ensure amostra_ifas table is correct
-- It should have ifa_id as BIGINT (which it does based on logs)
-- And it should probably reference ifa(id)
DO $$
BEGIN
    -- Check if we need to add the FK constraint
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.table_constraints 
        WHERE constraint_name = 'amostra_ifas_ifa_id_fkey'
    ) THEN
        -- Add FK constraint
        ALTER TABLE public.amostra_ifas 
        ADD CONSTRAINT amostra_ifas_ifa_id_fkey 
        FOREIGN KEY (ifa_id) 
        REFERENCES public.ifa(id);
    END IF;
END $$;

-- 4. Re-create triggers for ifa table
CREATE TRIGGER trg_log_delete_ifa
    AFTER DELETE ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_delete_ifa();

CREATE TRIGGER trg_log_insert_ifa
    AFTER INSERT ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_insert_ifa();

CREATE TRIGGER trg_log_update_ifa
    AFTER UPDATE ON public.ifa
    FOR EACH ROW
    EXECUTE FUNCTION log_update_ifa();
