// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfhebnctlsyiduwciiuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmaGVibmN0bHN5aWR1d2NpaXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTU2NDAsImV4cCI6MjA2NjUzMTY0MH0.jZSxkdzL5WHneLkGvnZhaI783wyP_orvVzKY5Rj-RIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});